export const CITIES = [
  { id: 'montreal', name: 'Montreal', country: 'Canada', flag: '🇨🇦', active: true, mapX: '27%', mapY: '38%' },
  { id: 'vancouver', name: 'Vancouver', country: 'Canada', flag: '🇨🇦', active: true, mapX: '15%', mapY: '36%' },
  { id: 'toronto', name: 'Toronto', country: 'Canada', flag: '🇨🇦', active: true, mapX: '25%', mapY: '39%' },
  { id: 'dubai', name: 'Dubai', country: 'UAE', flag: '🇦🇪', active: true, mapX: '60%', mapY: '50%' },
  { id: 'barcelona', name: 'Barcelona', country: 'Spain', flag: '🇪🇸', active: true, mapX: '46%', mapY: '42%' },
  { id: 'miami', name: 'Miami', country: 'USA', flag: '🇺🇸', active: false, mapX: '23%', mapY: '47%' },
  { id: 'new-york', name: 'New York', country: 'USA', flag: '🇺🇸', active: false, mapX: '24%', mapY: '41%' },
  { id: 'los-angeles', name: 'Los Angeles', country: 'USA', flag: '🇺🇸', active: false, mapX: '14%', mapY: '43%' },
]

export const PROPERTIES = [
  {
    id: 'le-moyne-heritage',
    name: 'Le Moyne Heritage',
    brand: 'Airstay',
    city: 'Montreal',
    country: 'Canada',
    neighbourhood: 'Downtown',
    type: 'Boutique Hotel',
    tag: 'Iconic',
    basePrice: 220,
    currency: 'CAD',
    bedrooms: '1–3',
    description: 'A 19th-century stone building with the legendary Central Perk lounge, exposed brick suites, and pool tables.',
    coverGradient: 'linear-gradient(155deg, #5C4A2A 0%, #1A1208 100%)',
    images: Array.from({length:9}, (_,i) => `/images/le-moyne-heritage/${i+1}.jpg`),
    amenities: ['Games Lounge', 'Pool Table', 'Fireplace', 'Exposed Brick', 'Full Kitchen'],
    rating: 4.97, reviews: 312,
  },
  {
    id: 'le-moyne-modern',
    name: 'Le Moyne Modern',
    brand: 'Airstay',
    city: 'Montreal',
    country: 'Canada',
    neighbourhood: 'Downtown',
    type: 'Boutique Hotel',
    tag: 'New 2024',
    basePrice: 265,
    currency: 'CAD',
    bedrooms: '1–3',
    description: 'Brand-new 2024 build. Double-height lofts, skylight atrium, rooftop terrace with fire pit and city panorama.',
    coverGradient: 'linear-gradient(155deg, #2C3E35 0%, #0D1A14 100%)',
    images: Array.from({length:9}, (_,i) => `/images/le-moyne-modern/${i+1}.jpg`),
    amenities: ['Rooftop Terrace', 'Fire Pit', 'Skylight', 'Marble Bathrooms', 'Resident Lounge'],
    rating: 4.99, reviews: 89,
  },
  {
    id: 'bishop',
    name: 'Bishop',
    brand: 'Airstay',
    city: 'Montreal',
    country: 'Canada',
    neighbourhood: 'Bishop Street',
    type: 'Boutique Hotel',
    tag: 'Most Distinctive',
    basePrice: 195,
    currency: 'CAD',
    bedrooms: '1–2',
    description: 'Victorian grandeur meets modern luxury. Dramatic black staircase, reception desk, golden lion crest.',
    coverGradient: 'linear-gradient(155deg, #1A1A1A 0%, #0A0A0A 100%)',
    images: Array.from({length:5}, (_,i) => `/images/bishop/${i+1}.jpg`),
    amenities: ['Reception & Concierge', 'Grand Staircase', 'Exposed Brick', 'Industrial Design'],
    rating: 4.95, reviews: 201,
  },
  {
    id: 'saint-paul',
    name: 'Saint-Paul',
    brand: 'Airstay',
    city: 'Montreal',
    country: 'Canada',
    neighbourhood: 'Old Montreal',
    type: 'Boutique Hotel',
    tag: 'Most Photographed',
    basePrice: 245,
    currency: 'CAD',
    bedrooms: '1–2',
    description: 'The iconic corner building with a living moss wall. Original 300-year-old stone walls inside.',
    coverGradient: 'linear-gradient(155deg, #1C3025 0%, #081510 100%)',
    images: Array.from({length:5}, (_,i) => `/images/saint-paul/${i+1}.jpg`),
    amenities: ['Living Moss Wall', 'Stone Walls', 'Walnut Kitchens', 'Old Montreal Views'],
    rating: 4.96, reviews: 178,
  },
  {
    id: 'notre-dame',
    name: 'Notre-Dame',
    brand: 'Airstay',
    city: 'Montreal',
    country: 'Canada',
    neighbourhood: 'Old Montreal',
    type: 'Boutique Hotel',
    tag: 'Most Romantic',
    basePrice: 210,
    currency: 'CAD',
    bedrooms: '1',
    description: 'Candlelit garden terrace, four-poster beds, original stone walls. The most romantic address in Old Montreal.',
    coverGradient: 'linear-gradient(155deg, #3D2A1A 0%, #150D06 100%)',
    images: Array.from({length:8}, (_,i) => `/images/notre-dame/${i+1}.jpg`),
    amenities: ['Garden Terrace', 'Four-Poster Beds', 'Stone Walls', 'Gold & Black Bathrooms'],
    rating: 4.98, reviews: 144,
  },
]

export const STATS = [
  { value: '50+', label: 'Properties Managed' },
  { value: '6', label: 'Countries' },
  { value: '4.9★', label: 'Average Rating' },
  { value: '1,200+', label: 'Happy Guests' },
  { value: '38%', label: 'Revenue Increase vs Self-Managed' },
  { value: '24/7', label: 'Guest & Owner Support' },
]

export const SERVICES = [
  {
    number: '01',
    title: 'Short-Term Rentals',
    desc: 'Fully managed boutique hotel experiences. Guest communications, cleaning, maintenance, pricing — we handle everything. Your property earns at its peak, every night.',
    icon: '🏨',
  },
  {
    number: '02',
    title: 'Long-Term Rentals',
    desc: 'Premium managed residences with flexible lease terms. Fully furnished, utilities coordinated, maintenance included. We find and vet tenants, handle renewals, manage everything.',
    icon: '🏠',
  },
  {
    number: '03',
    title: 'Property Management',
    desc: 'End-to-end building management for owners and investors. From a single unit to an entire building — we run it like a five-star operation.',
    icon: '🏢',
  },
  {
    number: '04',
    title: 'Maintenance Services',
    desc: 'Proactive maintenance, 24/7 emergency response, vetted contractor network. Every property under our care is maintained to an uncompromising standard.',
    icon: '🔧',
  },
]

export const WHY_OWN = [
  { title: 'Maximum Revenue', desc: 'Pricelabs dynamic pricing adjusts your rates in real-time against market demand. On average, our owners earn 38% more than self-managed properties.' },
  { title: 'Zero Hassle', desc: 'We handle guests, cleaning, maintenance, compliance, financial reporting, and everything in between. You receive a cheque and a report.' },
  { title: 'Full Transparency', desc: 'Real-time owner portal. Monthly performance reports. A dedicated manager who knows your property by name.' },
  { title: 'Your Asset Protected', desc: 'Vetted guests, smart noise monitoring, insurance compliance, and meticulous property care — your investment is in safe hands.' },
  { title: 'Global Reach', desc: 'Your property is listed across Airbnb, Booking.com, VRBO, direct channels, and our own growing global audience.' },
  { title: 'Technology-Driven', desc: 'Hostaway PMS + Pricelabs + Smart locks + AI messaging. The most advanced property management stack available today.' },
]
